/**
 * Generate a REAL match_proof and emit Rust const byte arrays (Stellar BN254 wire
 * encoding) for the zk_verifier integration test. Mirrors the relayer's exact
 * pricing math so the on-chain figures equal what the circuit proves.
 */
const path = require('path');
const fs = require('fs');
const snarkjs = require('snarkjs');
const circomlibjs = require('circomlibjs');

const BUILD = path.join(__dirname, '..', 'build');
const be32 = (dec) => BigInt(dec).toString(16).padStart(64, '0');
const g1Hex = (p) => be32(p[0]) + be32(p[1]);
const g2Hex = (p) => be32(p[0][1]) + be32(p[0][0]) + be32(p[1][1]) + be32(p[1][0]);
const hexToArr = (h) => { const b = []; for (let i = 0; i < h.length; i += 2) b.push(parseInt(h.substr(i, 2), 16)); return b; };
const arr = (h) => `[${hexToArr(h).join(',')}]`;

async function main() {
  const poseidon = await circomlibjs.buildPoseidon();
  const F = poseidon.F;

  const PRICE_SCALE = 1000000n;
  const buyer_price = 140000n, buyer_quantity = 5_000_000_000_000n, buyer_salt = 111n;
  const seller_price = 130000n, seller_quantity = 5_000_000_000_000n, seller_salt = 222n;
  const clearing_price = 135000n;                 // within [seller_price, buyer_price]
  const xlm_amount = 5_000_000_000_000n;
  const usdc_amount = (xlm_amount * clearing_price) / PRICE_SCALE;

  const buyer_commitment = F.toString(poseidon([buyer_price, buyer_quantity, 0n, buyer_salt]));
  const seller_commitment = F.toString(poseidon([seller_price, seller_quantity, 1n, seller_salt]));

  const input = {
    buyer_price: buyer_price.toString(), buyer_quantity: buyer_quantity.toString(), buyer_salt: buyer_salt.toString(),
    seller_price: seller_price.toString(), seller_quantity: seller_quantity.toString(), seller_salt: seller_salt.toString(),
    buyer_commitment, seller_commitment,
    clearing_price: clearing_price.toString(), xlm_amount: xlm_amount.toString(), usdc_amount: usdc_amount.toString(),
  };

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    path.join(BUILD, 'match_proof_js', 'match_proof.wasm'),
    path.join(BUILD, 'match_proof_final.zkey')
  );
  const vk = JSON.parse(fs.readFileSync(path.join(BUILD, 'match_proof_vk.json'), 'utf8'));
  if (!(await snarkjs.groth16.verify(vk, publicSignals, proof))) throw new Error('off-chain verify FAILED');

  const sigArr = publicSignals.map(s => arr(be32(s))).join(',\n    ');
  const icArr = vk.IC.map(p => arr(g1Hex(p))).join(',\n    ');
  const rs = `// AUTO-GENERATED by circuits/scripts/gen_match_vector.js — do not edit.
// Real match_proof groth16 proof, Stellar BN254 wire encoding.
pub const M_PI_A: [u8; 64] = ${arr(g1Hex(proof.pi_a))};
pub const M_PI_B: [u8; 128] = ${arr(g2Hex(proof.pi_b))};
pub const M_PI_C: [u8; 64] = ${arr(g1Hex(proof.pi_c))};
pub const M_SIGNALS: [[u8; 32]; ${publicSignals.length}] = [
    ${sigArr}
];
pub const M_VK_ALPHA: [u8; 64] = ${arr(g1Hex(vk.vk_alpha_1))};
pub const M_VK_BETA: [u8; 128] = ${arr(g2Hex(vk.vk_beta_2))};
pub const M_VK_GAMMA: [u8; 128] = ${arr(g2Hex(vk.vk_gamma_2))};
pub const M_VK_DELTA: [u8; 128] = ${arr(g2Hex(vk.vk_delta_2))};
pub const M_VK_IC: [[u8; 64]; ${vk.IC.length}] = [
    ${icArr}
];
`;
  const rsPath = path.join(__dirname, '..', '..', 'contracts', 'zk_verifier', 'src', 'match_vector.rs');
  fs.writeFileSync(rsPath, rs);
  console.log('off-chain verify: OK  nPublic', vk.nPublic, 'signals', publicSignals.length);
  console.log('publicSignals order:', publicSignals.join(', '));
  console.log('wrote', rsPath);
}
main().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
