/**
 * Generate a REAL groth16 proof from the compiled order_commitment circuit and
 * emit it (plus the verification key) encoded in Stellar's BN254 wire format:
 *   G1  = be(x) || be(y)                       (64 bytes)
 *   G2  = be(x.c1) || be(x.c0) || be(y.c1) || be(y.c0)   (128 bytes, imaginary-first)
 *   Fr  = be(scalar)                            (32 bytes)
 *
 * Output: circuits/build/test_vector.json  — consumed by the zk_verifier Rust test.
 */
const path = require('path');
const fs = require('fs');
const snarkjs = require('snarkjs');
const circomlibjs = require('circomlibjs');

const BUILD = path.join(__dirname, '..', 'build');

function be32(dec) {
  return BigInt(dec).toString(16).padStart(64, '0');
}
function g1Hex(p) {
  // snarkjs G1: [x, y, "1"]
  return be32(p[0]) + be32(p[1]);
}
function g2Hex(p) {
  // snarkjs G2: [[x.c0, x.c1], [y.c0, y.c1], ["1","0"]]
  // Stellar wants imaginary-first per Fp2: be(c1) || be(c0)
  return be32(p[0][1]) + be32(p[0][0]) + be32(p[1][1]) + be32(p[1][0]);
}

async function main() {
  const poseidon = await circomlibjs.buildPoseidon();
  const F = poseidon.F;

  const price = 140000n;
  const quantity = 5_000_000_000_000n;
  const direction = 0n;
  const salt = 12345678901234567890n;
  const commitment = F.toString(poseidon([price, quantity, direction, salt]));

  const input = {
    price: price.toString(),
    quantity: quantity.toString(),
    direction: direction.toString(),
    salt: salt.toString(),
    commitment,
  };

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    path.join(BUILD, 'order_commitment_js', 'order_commitment.wasm'),
    path.join(BUILD, 'order_commitment_final.zkey')
  );

  const vk = JSON.parse(fs.readFileSync(path.join(BUILD, 'order_commitment_vk.json'), 'utf8'));

  // Sanity: verify off-chain first
  const ok = await snarkjs.groth16.verify(vk, publicSignals, proof);
  if (!ok) throw new Error('off-chain verify FAILED — bad circuit artifacts');

  const out = {
    description: 'order_commitment real proof (Stellar BN254 wire encoding)',
    publicSignals, // decimal strings; [valid, commitment]
    proof_hex: {
      pi_a: g1Hex(proof.pi_a),
      pi_b: g2Hex(proof.pi_b),
      pi_c: g1Hex(proof.pi_c),
    },
    public_signals_hex: publicSignals.map(be32),
    vk_hex: {
      alpha: g1Hex(vk.vk_alpha_1),
      beta: g2Hex(vk.vk_beta_2),
      gamma: g2Hex(vk.vk_gamma_2),
      delta: g2Hex(vk.vk_delta_2),
      ic: vk.IC.map(g1Hex),
    },
  };
  fs.writeFileSync(path.join(BUILD, 'test_vector.json'), JSON.stringify(out, null, 2));

  // Also emit a Rust include file with const byte arrays (no hex parser needed in-test).
  const hexToArr = (h) => {
    const b = [];
    for (let i = 0; i < h.length; i += 2) b.push(parseInt(h.substr(i, 2), 16));
    return b;
  };
  const arr = (h) => `[${hexToArr(h).join(',')}]`;
  const icArr = out.vk_hex.ic.map(arr).join(',\n    ');
  const sigArr = out.public_signals_hex.map(arr).join(',\n    ');
  const rs = `// AUTO-GENERATED by circuits/scripts/gen_test_vector.js — do not edit.
// Real order_commitment groth16 proof, Stellar BN254 wire encoding.
pub const PI_A: [u8; 64] = ${arr(out.proof_hex.pi_a)};
pub const PI_B: [u8; 128] = ${arr(out.proof_hex.pi_b)};
pub const PI_C: [u8; 64] = ${arr(out.proof_hex.pi_c)};
pub const SIGNALS: [[u8; 32]; ${out.public_signals_hex.length}] = [
    ${sigArr}
];
pub const VK_ALPHA: [u8; 64] = ${arr(out.vk_hex.alpha)};
pub const VK_BETA: [u8; 128] = ${arr(out.vk_hex.beta)};
pub const VK_GAMMA: [u8; 128] = ${arr(out.vk_hex.gamma)};
pub const VK_DELTA: [u8; 128] = ${arr(out.vk_hex.delta)};
pub const VK_IC: [[u8; 64]; ${out.vk_hex.ic.length}] = [
    ${icArr}
];
`;
  const rsPath = path.join(__dirname, '..', '..', 'contracts', 'zk_verifier', 'src', 'test_vector.rs');
  fs.writeFileSync(rsPath, rs);
  console.log('wrote', rsPath);

  console.log('off-chain verify: OK');
  console.log('nPublic:', vk.nPublic, 'IC len:', vk.IC.length, 'signals:', publicSignals.length);
  console.log('wrote', path.join(BUILD, 'test_vector.json'));
}
main().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
